language: python

python:
  - "3.6"

cache: pip

services:
  - postgresql

env:
  - DJANGO=1.11

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


# command to run tests
script: python manage.py test
